In [1]:
import xarray as xr
fname = '/home/dnash/cwp140/data/preprocessed/SEAK-WRF/ccsm/hist/trends/snow_ccsm_ONDJFM_strict_ros_frequency_clim.nc'
ds = xr.open_dataset(fname)
ds

<xarray.Dataset> Size: 4MB
Dimensions:   (y: 250, x: 320)
Coordinates:
    lat       (y, x) float32 320kB ...
    lon       (y, x) float32 320kB ...
Dimensions without coordinates: y, x
Data variables:
    ros       (y, x) float64 640kB ...
    pcpt      (y, x) float64 640kB ...
    delsnow   (y, x) float64 640kB ...
    snow      (y, x) float64 640kB ...
    ivt       (y, x) float64 640kB ...
    delsnowh  (y, x) float64 640kB ...
Attributes:
    long_name:    Rain-on-snow event
    description:  1 = ROS event
    units:        ROS (d yr$^{{-1}}$)

In [2]:
import os, sys
import pandas as pd

sys.path.append('../modules/')
import globalvars

fname = globalvars.path_to_data + 'downloads/SEAK_News_Reported_Landslides.csv'
df = pd.read_csv(fname)
df = df.set_index(pd.to_datetime(df['Day_min']))
## subset to dates between 2000 and 2024
idx = (df.index >= '1980-01-01') & (df.index <= '2019-12-31')
df = df.loc[idx]
df

/scratch/dnash/job_1334307/ipykernel_130317/3243156012.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = df.set_index(pd.to_datetime(df['Day_min']))

,Art_ID,LS_ID,Day_min,Day_max,Day_prc,Time_class,Time_min,Time_max,Time_per_min,Time_per_max,...,Pub_day,News_source,Article_link_1,Article_link_2,Article_link_3,Article_link_4,Article_link_5,Article_link_6,Article_link_7,Comments
Day_min,,,,,,,,,,,,,,,,,,,,,
2014-09-18,1,1,9/18/14,9/19/14,Two days,Approximate,NaN,NaN,Night,Morning,...,9/26/14,KTOO,https://www.ktoo.org/2014/09/26/landslide-dest...,https://kcaw-org.s3.amazonaws.com/wp-content/u...,https://www.ketchikandailynews.com/news/alaska...,https://newspaperarchive.com/daily-sitka-senti...,NaN,NaN,NaN,NaN
2014-09-18,1,2,9/18/14,9/19/14,Two days,Approximate,NaN,NaN,Night,Morning,...,9/26/14,KTOO,https://www.ktoo.org/2014/09/26/landslide-dest...,https://kcaw-org.s3.amazonaws.com/wp-content/u...,https://www.ketchikandailynews.com/news/alaska...,https://newspaperarchive.com/daily-sitka-senti...,NaN,NaN,NaN,NaN
2014-09-18,1,3,9/18/14,9/19/14,Two days,Approximate,NaN,NaN,Night,Morning,...,9/26/14,KTOO,https://www.ktoo.org/2014/09/26/landslide-dest...,https://kcaw-org.s3.amazonaws.com/wp-content/u...,https://www.ketchikandailynews.com/news/alaska...,https://newspaperarchive.com/daily-sitka-senti...,NaN,NaN,NaN,NaN
2015-01-21,14,26,1/21/15,1/21/15,Daily,Approximate,NaN,NaN,Afternoon,Afternoon,...,1/21/15,KTOO,https://www.ktoo.org/2015/01/21/dot-cleans-sma...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-06,15,27,10/6/19,10/6/19,Daily,Not listed,NaN,NaN,NaN,NaN,...,10/7/19,KTOO,https://www.ktoo.org/2019/10/07/heavy-rain-ext...,https://www.juneauempire.com/news/flooding-in-...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990-10-07,98,150,10/7/90,10/11/90,Weekly,Not listed,NaN,NaN,NaN,NaN,...,10/15/90,DSS,https://newspaperarchive.com/daily-sitka-senti...,https://newspaperarchive.com/daily-sitka-senti...,NaN,NaN,NaN,NaN,NaN,NaN
1992-11-29,99,151,11/29/92,11/29/92,Daily,Not listed,NaN,NaN,NaN,NaN,...,12/2/92,DSS,https://newspaperarchive.com/daily-sitka-senti...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2002-07-10,101,152,7/10/02,7/20/02,Monthly,Not listed,NaN,NaN,NaN,NaN,...,7/31/02,DSS,https://newspaperarchive.com/daily-sitka-senti...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2003-10-25,102,153,10/25/03,10/25/03,Daily,Approximate,NaN,NaN,Evening,Evening,...,10/30/03,DSS,https://newspaperarchive.com/daily-sitka-senti...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-02-15,107,159,2/15/17,2/15/17,Daily,Not listed,NaN,NaN,NaN,NaN,...,2/15/17,JE,https://www.juneauempire.com/news/mudslide-dam...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1]:
import pandas as pd
fname = '../out/landslide_summary_strict.csv'
df = pd.read_csv(fname)
df

    start_date    end_date        lat         lon  max_ros  max_ar
0   2014-09-17  2014-09-20  57.127056 -135.312776      NaN     1.0
1   2014-09-17  2014-09-20  57.133746 -135.343221      NaN     1.0
2   2014-09-17  2014-09-20  57.127861 -135.350486      NaN     1.0
3   2015-01-20  2015-01-22  58.316395 -134.446995      1.0     1.0
4   2019-10-05  2019-10-07  58.306947 -134.404521      NaN     1.0
..         ...         ...        ...         ...      ...     ...
72  1990-10-06  1990-10-12  57.093259 -135.353256      NaN     1.0
73  1992-11-28  1992-11-30  55.406803 -131.726241      0.0     1.0
74  2002-07-09  2002-07-21  58.312093 -134.663863      NaN     1.0
75  2003-10-24  2003-10-26  55.454708 -133.052113      NaN     1.0
76  2017-02-14  2017-02-16  58.286993 -134.414134      1.0     1.0

[77 rows x 6 columns]

In [5]:
ros_total = (df['max_ros'].sum() / len(df))*100
ar_total = (df['max_ar'].sum() / len(df))*100
print(f"ROS freq: {df['max_ros'].sum()}")
print(f"AR freq: {df['max_ar'].sum()}")
print(f"ROS: {ros_total}%, AR: {ar_total}%")

ROS freq: 6.0
AR freq: 70.0
ROS: 7.792207792207792%, AR: 90.9090909090909%

In [4]:
len(df)

77

In [6]:
6/77

0.07792207792207792